name: Unzip project

on:
  push:
    branches: [ "main" ]

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip project.zip
        run: |
          unzip project.zip -d .
      
      - name: Remove zip file
        run: rm project.zip

      - name: List files (debug)
        run: ls -la
